stages:
  - build
  - unit_test

variables:
  PROJECT_NAME: chowtown
  PRODUCTION_VERSION: "1.0.0"
  DOCKER_IMAGE_NAME: "daniel413x/$PROJECT_NAME-client"

cache:
  - key:
      files:
          - package-lock.json
    paths:
      - node_modules/

build app:
  except:
    - main
    - staging
  image: node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
    - echo $APP_VERSION > version.html
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

unit test app:
  except:
    - main
    - staging
  image: node:18-alpine
  stage: unit_test
  script:
    - npm run test
